//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5456
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpServer.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorFilePaths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorFilePaths() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HttpServer.Resources.ErrorFilePaths", typeof(ErrorFilePaths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /OutOfMemory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EM001 {
            get {
                return ResourceManager.GetString("EM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /401 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP401 {
            get {
                return ResourceManager.GetString("EP401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /403 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP403 {
            get {
                return ResourceManager.GetString("EP403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /404 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP404 {
            get {
                return ResourceManager.GetString("EP404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /500 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EP500 {
            get {
                return ResourceManager.GetString("EP500", resourceCulture);
            }
        }
    }
}
